### ISSUE TITLE
Part of the content of ami_models is missing

### ISSUE THREAD

**Issue by qipotianMFXT** [acmi-lab/modular-summarization#5]
"Hello, when I was reproducing your paper, after downloading and extracting the ami_models, when I ran the command ./predict_ami.sh, there were many FileNotFoundError errors because all the files with .jsonl suffix were missing. Could you provide the complete ami_models?"

**Comment by kukrishna** [comment]
Hi,

Did you run the dataset preparation script (prepare_data.sh) before running the prediction script?
If not running that should solve the problem. If it doesn't please provide the error log containing which filenames were mentioned in the error in which lines

Thanks

**Comment by qipotianMFXT** [comment]
> Hi,
> 
> Did you run the dataset preparation script (prepare_data.sh) before running the prediction script? If not running that should solve the problem. If it doesn't please provide the error log containing which filenames were mentioned in the error in which lines
> 
> Thanks

Excuse me, if I do not run the dataset preparation script (prepare_data.sh) before running the prediction script, the following information is provided about missing files：

FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_base/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_small/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_sectionwise_conditioned_t5_small/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_allxmins_fullsummary_t5_small/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_base/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_small/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_sectionwise_conditioned_t5_small/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_allxmins_fullsummary_t5_small/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 221, in evaluate_rouge
    fullsummary_comparisions = get_full_comparisions_dict(dataset, split, algo, dataset_dir, eval_objs)
  File "calculate_rouge.py", line 40, in get_full_comparisions_dict
    with open(ground_truth_fpath, "r", encoding="utf-8") as src:
**FileNotFoundError: [Errno 2] No such file or directory: 'dataset_ami/full_summarization/test.jsonl'**

**Comment by qipotianMFXT** [comment]
> Hi,
> 
> Did you run the dataset preparation script (prepare_data.sh) before running the prediction script? If not running that should solve the problem. If it doesn't please provide the error log containing which filenames were mentioned in the error in which lines
> 
> Thanks

Besides, if I  run the dataset preparation script (prepare_data.sh) before running the prediction script, the following information is provided about missing files：

Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_base/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_small/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_sectionwise_conditioned_t5_small/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_allxmins_fullsummary_t5_small/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/pg_models/ser_fullconversation_fullsummary/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 
'**./ami_models/pg_models/ser_allxmins_fullsummary/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/pg_models/ser_sectionwise_allxmins_sectionsummary/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/pg_models/ser_entrywise_summarization/test_outputs.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_base/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_entrywise_conditioned_t5_small/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_sectionwise_conditioned_t5_small/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/t5_models/ser_allxmins_fullsummary_t5_small/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/pg_models/ser_allxmins_fullsummary/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/pg_models/ser_sectionwise_allxmins_sectionsummary/test_outputs_on_hlstm.jsonl'**
Traceback (most recent call last):
  File "calculate_rouge.py", line 281, in <module>
    result_df = evaluate_rouge(rouge_impl, dataset, split, algo, dataset_dir, eval_file)
  File "calculate_rouge.py", line 212, in evaluate_rouge
    with open(eval_file,"r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: **'./ami_models/pg_models/ser_entrywise_summarization/test_outputs_on_hlstm.jsonl'**

**Comment by kukrishna** [comment]
Hi,

I received another issue about missing files. It turns out that due to the update in python version on google colab, some APIs have changed and do not work.
So the missing files that you are seeing are likely due to a crash in some prior script in the sequence which was supposed to create those files.

For example, with the current python version (3.10) on colab, the xml library's api has changed and hence 
the code to create the dataset files crashes with the error:
```
Traceback (most recent call last):
  File "/content/modular-summarization/dataset_creators/AMI/create_dataset.py", line 43, in <module>
    all_people_roles = get_roles()
  File "/content/modular-summarization/dataset_creators/AMI/create_dataset.py", line 27, in get_roles
    meetings=xmlroot.getchildren()
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

I would suggest running the code with python version 3.6
If some errors still show up, please share the *first* error that you get while running the given sequence of commands.
